extends SceneTree
const ChessGame = preload("res://scripts/chess/chess_game.gd")
const MoveResult = preload("res://scripts/chess/move_result.gd")
func _init() -> void: call_deferred("_run")
func _run() -> void:
	var game = ChessGame.new()
	assert(game.try_uci("e2e4") != null)
	assert(game.try_uci("e7e5") != null)
	assert(game.try_uci("e1e3") == null)
	assert(game.move_history == ["e2e4", "e7e5"])
	assert(game.san_history == ["e4", "e5"])
	assert(game.to_pgn({"White": "Player", "Black": "Stockfish"}).contains("1. e4 e5 *"))
	assert(game.undo_last_move() == "e7e5")
	assert(game.state.to_fen() == "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1")
	assert(game.undo_last_move() == "e2e4" and game.state.to_fen() == "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1")
	var capture_game = ChessGame.new()
	capture_game.try_uci("e2e4")
	capture_game.try_uci("d7d5")
	var capture = capture_game.try_uci("e4d5")
	assert(capture.is_capture and capture.captured_piece == -1)
	assert(capture_game.san_history.back() == "exd5")
	assert(capture is MoveResult and capture.before_fen != capture.after_fen)
	var ep_game = ChessGame.new()
	for uci in ["e2e4", "a7a6", "e4e5", "d7d5"]:
		assert(ep_game.try_uci(uci) != null)
	var ep = ep_game.try_uci("e5d6")
	assert(ep != null and ep.is_en_passant and ep.en_passant_capture_square == 35 and ep.captured_piece == -1)
	assert(ep_game.state.get_piece(35) == 0 and ep_game.state.get_piece(43) == 1)
	var promotion_game = ChessGame.new("7k/P7/8/8/8/8/8/7K w - - 99 1")
	var promotion = promotion_game.try_uci("a7a8q")
	assert(promotion != null and promotion.is_promotion and promotion.promotion_piece_type == 5)
	assert(promotion_game.state.halfmove_clock == 0 and promotion_game.state.get_piece(56) == 5)
	var promotion_capture_game = ChessGame.new("1r5k/P7/8/8/8/8/8/7K w - - 0 1")
	var promotion_capture = promotion_capture_game.try_uci("a7b8r")
	assert(promotion_capture != null and promotion_capture.is_capture and promotion_capture.is_promotion)
	assert(promotion_capture_game.state.get_piece(57) == 4)
	assert(promotion_capture_game.san_history.back() == "axb8=R+")
	var check_game = ChessGame.new("7k/8/8/8/8/8/6Q1/K7 w - - 0 1")
	assert(check_game.try_uci("g2g7").gives_check)
	var fifty_game = ChessGame.new("7k/8/8/8/8/8/1Q6/K7 w - - 99 1")
	assert(fifty_game.try_uci("b2b3").game_result == "draw_fifty_move")
	assert(ChessGame.new("7k/8/8/8/8/8/8/K7 w - - 0 1").game_result() == "draw_insufficient_material")
	assert(ChessGame.new("7k/8/8/8/8/8/8/KN6 w - - 0 1").game_result() == "draw_insufficient_material")
	assert(ChessGame.new("7k/8/8/8/8/8/8/KB6 w - - 0 1").game_result() == "draw_insufficient_material")
	assert(ChessGame.new("7k/8/8/8/8/8/8/KB5b w - - 0 1").game_result() == "draw_insufficient_material", "Same-colour bishops are a dead position.")
	assert(ChessGame.new("7k/8/8/8/8/8/8/KN4n1 w - - 0 1").game_result() == "ongoing", "Opposing knights can participate in a legal mating position.")
	assert(ChessGame.new("7k/8/8/8/8/8/8/KB4n1 w - - 0 1").game_result() == "ongoing", "Mixed opposing minors are not automatically dead.")
	var repetition_game = ChessGame.new()
	for uci in ["g1f3", "g8f6", "f3g1", "f6g8", "g1f3", "g8f6", "f3g1", "f6g8"]:
		assert(repetition_game.try_uci(uci) != null)
	assert(repetition_game.game_result() == "draw_threefold_repetition")
	print("PASS: ChessGame UCI submission.")
	quit()
