extends SceneTree
const Controller = preload("res://scripts/game/turn_controller.gd")
func _init() -> void: call_deferred("_run")
func _run() -> void:
	var controller = Controller.new()
	controller.start()
	assert(controller.submit_uci("e2e4") != null)
	assert(controller.submit_uci("e7e5") == null)
	controller.presentation_finished()
	assert(controller.submit_uci("e7e5") != null)
	controller.presentation_finished()
	assert(controller.begin_engine_turn())
	assert(controller.phase == Controller.Phase.ENGINE_THINKING)
	assert(controller.submit_uci("g1f3") == null, "Human submission must remain locked while the engine thinks.")
	assert(controller.submit_engine_uci("g1f3") != null)
	assert(controller.phase == Controller.Phase.PRESENTING_MOVE)
	controller.free()
	print("PASS: turn phase locks move input.")
	quit()
